01.out: 01.c
	@cc -g 01.c -o 01.out

02.out: 02.c
	@cc -g 02.c -o 02.out

03.out: 03.c
	@cc -g 03.c -o 03.out

04.out: 04.c
	@cc -g 04.c -o 04.out

sol01: 01.out
	@./01.out < 01.txt

sol02: 02.out
	@./02.out < 02.txt

sol03: 03.out
	@./03.out < 03.txt

sol04: 04.out
	@./04.out < 04.txt
